import { generateWithGemini } from './gemini';

export const GEMINI_REVIEWER_SYSTEM_PROMPT = `You are the Second Opinion Reviewer for a B2B branding agency.
Your job is to review the Final Lead Decision output generated by the primary AI.
Look for:
- Hallucinated fields (e.g. clearly fake emails, weird websites)
- Contact assigned to wrong person
- Compliance contact incorrectly treated as primary marketing contact
- Contradictions in the data

Output JSON:
{
  "agree": true/false,
  "issues": ["list of issues found"],
  "suggestedCorrections": ["list of suggestions"],
  "confidenceAdjustment": -10 or 0,
  "notes": "Brief explanation"
}`;

export async function executeGeminiReviewer(evidencePack: any, finalDecision: any) {
  const prompt = `Evidence Pack summary:
${JSON.stringify({ 
  companies: evidencePack.companyCandidates, 
  websiteDocs: evidencePack.businessDescriptionEvidence 
}, null, 2).substring(0, 2000)}

Final Decision Output:
${JSON.stringify(finalDecision, null, 2)}

Review the Final Decision output against the summary evidence and provide your second opinion in JSON format.`;

  try {
    const result = await generateWithGemini(prompt, {
      systemPrompt: GEMINI_REVIEWER_SYSTEM_PROMPT
    });

    // Strip backticks if any
    const jsonMatch = result.match(/\{[\s\S]*\}/);
    if (!jsonMatch) return null;

    return JSON.parse(jsonMatch[0]);
  } catch (error) {
    console.error('Gemini second opinion failed:', error);
    return null;
  }
}
